spring:
  application:
    name: "pure-cqrs-axon"
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:cqrs
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  main:
    allow-circular-references: true
